M48
; DRILL file {KiCad (7.0.0-rc2-19-gbcc1e28bab)} date Thu Jan 26 23:12:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-26T23:12:18-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-rc2-19-gbcc1e28bab)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.7209Y-3.0059
X3.7209Y-3.1968
T2
X3.6016Y-2.9941
X3.6016Y-3.2086
T0
M30
